### ISSUE TITLE
error exporting sbml with explicit level and version

### ISSUE THREAD

**Issue by pmendes** [copasi/basico#44]
I try saving sbml to a different level and version (in this case level 3 and version 1). I get:

```
Traceback (most recent call last):
  File "/home/mendes/Copasi/model_replicator/./sbmodelr", line 668, in <module>
    save_model(filename=newfilename, type='sbml', sbml_level=sbmll, sbml_version=sbmlv, model=newmodel)
  File "/home/mendes/.local/lib/python3.9/site-packages/basico/model_io.py", line 488, in save_model
    if not exporters[file_type](filename):
  File "/home/mendes/.local/lib/python3.9/site-packages/basico/model_io.py", line 470, in <lambda>
    'sbml': lambda filename: model.exportSBML(filename, overwrite, sbmlLevel=sbml_level, sbmlVersion=sbml_version,
  File "/home/mendes/.local/lib/python3.9/site-packages/COPASI/__init__.py", line 18604, in exportSBML
    return _COPASI.CDataModel_exportSBML(self, fileName, overwriteFile, sbmlLevel, sbmlVersion, exportIncomplete, exportCOPASIMIRIAM, pProcessReport)
TypeError: Wrong number or type of arguments for overloaded function 'CDataModel_exportSBML'.
  Possible C/C++ prototypes are:
    CDataModel::exportSBML(std::string const &,bool,int,int,bool,bool,CProcessReport *)
    CDataModel::exportSBML(std::string const &,bool,int,int,bool,bool)
    CDataModel::exportSBML(std::string const &,bool,int,int,bool)
    CDataModel::exportSBML(std::string const &,bool,int,int)
    CDataModel::exportSBML(std::string const &,bool,int)
    CDataModel::exportSBML(std::string const &,bool)
    CDataModel::exportSBML(std::string const &)
```

**Comment by pmendes** [comment]
Sorry, this is not a bug in basico. My variables sbmll and sbmlv were strings...
